language: python
python:
  - "2.7"
  - "3.4"
cache:
  - pip
  - apt

addons:
  apt:
    packages:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - swig

install: "pip install -r requirements.txt"
script: "bash run_tests.sh"